### ISSUE TITLE
Not working with React.memo (`trackAllPureComponents: true`) in Next.js

### ISSUE THREAD

**Issue by DaniGuardiola** [welldone-software/why-did-you-render#177]
I've already reported it to the Next repo, [here's the issue with all of the info + minimal repro](https://github.com/vercel/next.js/issues/21328).

I don't know if I'm doing something wrong here, but I'm not getting any logs.

**Comment by vzaidman** [comment]
I suggest closing it there. it's up to me to investigate and fix it.

**Comment by DaniGuardiola** [comment]
@vzaidman okay, done, thanks. By the way, I'm creating a more extensive repro and I'm realizing this might not work as I think it does. I'll push it soon.

**Comment by DaniGuardiola** [comment]
Update: here's the updated repro https://github.com/DaniGuardiola/next-wdyr-bug-repro/

Should be self-explanatory. Only the `ExplicitState` component gets a log.

**Comment by vzaidman** [comment]
ok thanks

**Comment by DaniGuardiola** [comment]
I just discovered something very weird, it seems to work (almost) fine with experimental `react` and `react-dom` versions. I've updated the repro above to make it more detailed.

To switch to experimental:

```
yarn add react@experimental react-dom@experimental
```

To go back:

```
yarn add react@latest react-dom@latest
```

**Comment by vzaidman** [comment]
@DaniGuardiola I finally managed to get to it and fix the example you showed.
here is the PR with the changes required: https://github.com/DaniGuardiola/next-wdyr-bug-repro/pull/1
the issue comes from the latest Next.js using the new JSX transform.

Before closing the issue:
1. I'm going to update the example in Next.js
2. I'm going to add a link to the example in Next.js from the readme

**Comment by vzaidman** [comment]
opened a PR on next.js: https://github.com/vercel/next.js/pull/21651
