### ISSUE TITLE
How to keep the renderer's DisplayName when using a Hoc 

### ISSUE THREAD

**Issue by SimaAmini** [welldone-software/why-did-you-render#192]
I created a HOC to wrap my components to use why-did-you-render wherever I want.
here's the code:
```
import React from 'react';

export const withWdyr = (Component, options = {}) => (props) => {
  Component.whyDidYouRender = {
    logOnDifferentValues: true,
    customName: options.displayName || Component.name || 'Component',
  };

  return <Component {...props} />;
};
```
and this is how I use it in a component:
```
const TestWrapped = () => {
// some code
}

const Test= withWdyr(TestWrapped , {
  displayName: 'Test',
});
export { Test };
```
logs:
![test](https://user-images.githubusercontent.com/12030102/116341167-add25180-a7f5-11eb-9017-b6a78079fb8a.png)

As you can see I can not find out who actually rendered the component in the logs (**Rendered by Unknown**). I wonder if it's possible to keep the actual renderer's name to make the logs more useful.

**Comment by vzaidman** [comment]
I see that `withWdyr` works for you.

Regarding to the `Unknown` component, the problem is a widespread React problem that you can see just as good if you open the React Dev Tools:

Here are two ways to keep the component's name:
create them as functions
```
function MenuGridItems() {
   return div somthing div
})

// or
return React.memo(function MenuGridItems() {
   return div somthing div
})
```
and
```
const Test = () => {
// some code
}
```
should actually work.

What **doesn't work** usually is:
```
export const SomeName = React.memo(() => {
});
```
How is your `Unknown` component exported?

https://github.com/welldone-software/why-did-you-render/issues/163
