### ISSUE TITLE
`trackExtraHooks` needed for custom hooks defined in my own code?

### ISSUE THREAD

**Issue by justingrant** [welldone-software/why-did-you-render#210]
I create a lot of custom hooks in my project. Do I need to add them all into `trackExtraHooks` to get WDYR to track them?  Or is `trackExtraHooks` only for hooks exported from outside my code?

**Comment by vzaidman** [comment]
Custom hooks are always dependent upon basic React hooks. If you add custom hooks to `trackExtraHooks`, you will receive tracking of them besides the tracking of the basic ones.

So, for example, if I have:
```jsx
useSomething(...args) {
  return useState(...args);
}
```

It would track useState anyway, but if you add `useSomething` to the list of custom hooks, it will be tracked instead.

Eventually- it's up to you to decide what custom hooks to add to the list.

I'd say, just add the ones that are suspect of slowing down the app, the ones that are reused the most, the ones that come from libraries that are used in many places in the code, etc...

**Comment by justingrant** [comment]
I tried to add my own hooks but got the  `trackExtraHooks cannot set property of #<Object> which has only a getter` error discussed in #85 for external hooks. My app is using Webpack via create-react-app.

#85 discusses using non-ESM imports to work around this problem, but for my own code I'm not sure how to do that. Any ideas?

**Comment by vzaidman** [comment]
The only workaround I can think of is to export the hooks on an object like this:

```
const obj = {
  useSomething: () => {...}
}

export default obj;
```

The problem is that you can't replace an esm export with another export (which is what the WDYR library does) because these exports are read-only.

You can also try exporting your hooks using `module.exports = obj`

To be honest, I wouldn't put any time and effort into it. I think it will not give you much anyway.
