### ISSUE TITLE
Using WDYR alongside another lib that needs to hook into `importSource`

### ISSUE THREAD

**Issue by acnebs** [welldone-software/why-did-you-render#229]
I'm using the new automatic JSX transform. To use it with WDYR, you need to set the `importSource` for `@babel/preset-react` to a WDYR-specific value, as described [here](https://github.com/welldone-software/why-did-you-render#setup). 

However, I am also using the Emotion library with their CSS prop. Likewise, for compatibility with the new automatic JSX runtime, they require the same: `importSource` to be set to an Emotion-specific value, as seen [here](https://emotion.sh/docs/css-prop#babel-preset).

Is there a way to have these two libs coexist when using the new automatic JSX transform/runtime?

**Comment by vzaidman** [comment]
Sadly, the answer is that currently **there's no way**.

I think there might be a way to achieve that.

If anybody wants to contribute one- they are welcome.

**Comment by TimonLukas** [comment]
I stumbled onto this issue when trying to integrate `why-did-you-render` into a Vite project with React 18 that already uses `@emotion/react`. Although quite hacky, I found a workaround - it's not perfect, but it seems to work as expected & can surely be improved, so I'll describe the steps here. Please let me know if you find improvements!

1. Add this package as a dev dependency
2. Next we'll create custom JSX dev/prod runtimes. Choose some location - I created the folder `/jsx/wdyr` for this purpose.
3. In this folder, create three files:
   1. `jsx-runtime.ts`
      ```typescript
      export *  from "react/jsx-runtime"
      export *  from "@emotion/react/jsx-runtime"
      export { JSX } from "@emotion/react/jsx-runtime"
      ```
   2. `jsx-dev-runtime.ts`
      ```typescript
      import runtime from 'react/jsx-dev-runtime'
      // @ts-expect-error Inaccurate type definitions
      import { jsxDEV } from "@welldone-software/why-did-you-render/jsx-dev-runtime"
      runtime.jsxDEV = jsxDEV
      // @ts-expect-error Inaccurate type definitions
      export { jsxDEV, Fragment } from "@emotion/react/jsx-dev-runtime"
      ```
   3. `index.ts`
      ```typescript
      export * from "./jsx-runtime"
      ```
4. In your `vite.config.ts`, set the `jsxImportSource` option of the `@vitejs/plugin-react` plugin to `/jsx/wdyr` (or whatever your folder is).
5. Add a file `src/wdyr.ts`:
   ```typescript
   import React from 'react';
   
   if (import.meta.env.DEV) {
       const wdyr = (await import('@welldone-software/why-did-you-render')).default;
       wdyr(React, {
           trackAllPureComponents: true,
       });
   }
   ```
6. Import the previous file first thing in your `index.tsx`

This makes `why-did-you-render` work as expected during development while not being included in the production build.

**Important: if you make changes to your custom JSX runtime files, make sure to delete `node_modules/.vite`, otherwise it might still use the old version.**

### Explanation

`jsx-runtime.ts`

It feels like exporting everything from `@emotion/react/jsx-runtime` should be enough, but if I don't first export everything from `react/jsx-runtime`, production builds fail with errors about e.g. `createElement` being missing. If I export everything from both TS complains about `JSX` being exported by both, so I also export it explicitly.

`index.ts`

Without this file, the production build fails (apparently it looks at just `/jsx/wdyr`).

`jsx-dev-runtime.ts`

`@emotion/react` calls the `jsxDEV` method from `react/jsx-runtime`. By first replacing this method with the modified one from `why-did-you-render` we make sure both are called.

`/jsx/wdyr` folder

The `jsxImportSource` must resolve during dev and build. Relative paths don't work (since it's injected without resolving the path), and aliases don't work during build. An absolute path (relative to the project root) works in both situations.

### Remaining issues

In dev mode, Vite will write the following warnings to the console:

```
Failed to resolve dependency: /jsx/wdyr/jsx-dev-runtime, present in client 'optimizeDeps.include'
Failed to resolve dependency: /jsx/wdyr/jsx-runtime, present in client 'optimizeDeps.include'
```

I haven't found a way to properly fix them, but they don't seem to be causing any harm.
