### ISSUE TITLE
Eslint plugin

### ISSUE THREAD

**Issue by yantakus** [welldone-software/why-did-you-render#34]
Just an idea - create an eslint plugin that helps users prevent common mistakes that cause unnecessary rerenders like `<Component style={{ background: 'black' />`.

**Comment by vzaidman** [comment]
The thing it's not always a bad idea-
only for chosen components which are rendered frequantly

**Comment by yantakus** [comment]
There are other cases that are easy to track and fix, for example `<Component onClick={() => handleClick()} />` instead of `<Component onClick={handleClick} />`. And I'm sure there are much more scenarios like this.

**Comment by vzaidman** [comment]
@yantakus don't get the impression it's something that always has to happen throughout the whole app.

If you have an APP component that is not connected to anything like "Redux", you know it renders only once, you don't need to worry about these things.

so as a big list of items that is pure-

The list itself is pure, so it renders only once, the children of that list might have style={{}} and onClick={() => {}} because the list guarantees they are rendered and re-rendered only when it's necessary.

**Comment by vzaidman** [comment]
by the way, theres soimething like this already:
https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/jsx-no-bind.md

**Comment by JustFly1984** [comment]
There is eslint-plugin-react-perf which covers a lot of use cases
