### ISSUE TITLE
[Typescript] React Components doesn't have whyDidYouRender static member on them

### ISSUE THREAD

**Issue by vzaidman** [welldone-software/why-did-you-render#59]
more about the issue:
https://www.reddit.com/r/typescript/comments/d3nw6j/advanced_ts_replacing_a_class_with_an_extended/

progress made in:
https://github.com/welldone-software/why-did-you-render/tree/improve-types

**Comment by vzaidman** [comment]
fixed in 3.5.5

**Comment by clintharris** [comment]
Thank you for sharing the Reddit link! I had the same question while working on #56 but didn't have time to research further--interesting lesson-learned.

**Comment by vzaidman** [comment]
I think it only half solves it but I'm afraid it's the best solution.
My IDE doesn't fully supports it but at least going `whyDidYouRender = 'aa'` on a class throws an error.

**Comment by zmnv** [comment]
> fixed in 3.5.5

where is 3.5.5 ? Is it a version of your package or typescript?

I have typescript 3.6.4 and get the same issue

**Comment by vzaidman** [comment]
in version 3.5.5 of the library (and the versions after it)

**Comment by vasilii-kovalev** [comment]
My setup is [CRA](https://github.com/facebook/create-react-app) + [TypeScript](https://github.com/microsoft/TypeScript) + [react-hot-loader](https://github.com/gaearon/react-hot-loader) + [react-app-rewire-hot-loader](https://github.com/cdharris/react-app-rewire-hot-loader). Version of WDYR is `4.2.7`. Still had the issue.

The only way to solve it for me was to add a types reference to `react-app-env.d.ts`.

I also shared it on Stack Overflow: https://stackoverflow.com/a/63323949/11293963

**Comment by vzaidman** [comment]
what do you mean "React and React DOM are patched" ?

**Comment by vasilii-kovalev** [comment]
[To enable](https://github.com/cdharris/react-app-rewire-hot-loader#usage) `react-app-rewire-hot-loader`, it is necessary to change `react-scripts` to `react-app-rewired`. As I understand that, it allows to change some parts of webpack configuration, changing links to React/React DOM implementations (like in [this example](https://github.com/cdharris/react-app-rewire-hot-loader/issues/23#issuecomment-485193878)).

Now I see that's a wrong idea, because such webpack config changes can't affect type checking. Now I commented out all the places where `react-app-rewire-hot-loader` or any type of hot reloading is used and it still doesn't work without my solution...

**Comment by amirsarfarW** [comment]
Is it available to add a feature that enable us to include a component and all its descendent (children) components?

For example I have this code

```
<Parent>
  <A>
    <B>
      <C>Hello</C>
    </B>
  </A>
</Parent>
```

I want to be able to include `A` and all its children (in this case `A`, `B` & `C`)

In large pages it is very difficult to include a section and its children with regex and it is almost impossible to track all components
