### ISSUE TITLE
Is there a command to initalise plugin to report on all component without adding statics

### ISSUE THREAD

**Issue by delp--** [welldone-software/why-did-you-render#76]
QUESTION - 
It would be great to be able to add the plugin then have it report on **all** components and if it was too noisy in the console then they could be turned off/excluded individually.
This would save having to add statics into each file that wished to monitor.

Is this possible?

**Comment by vzaidman** [comment]
Before I say yes, I strictly suggest **not doing so**.

I suggest using this library only for components you explicitly decided to track instead of the opposite since not every small re-render is problematic.

If you still want to do it with:
```
whyDidYouRender(React, {
    include: [/.*/]
})
```
And then specifically exclude components: (make sure to update WDYR, i just added this feature a moment ago)
```
class ExcludedTestComponent extends React.Component{
  static whyDidYouRender = false
  render(){
    return <div>hi!</div>
  }
}
```
or
```
const ExcludedTestComponent = () => <div>hi!</div>
ExcludedTestComponent.whyDidYouRender = false
```

**Comment by delp--** [comment]
Thank you. Warning noted :)

I guess with experience in debugging these re-renders things will become clearer. It will be great to see the list of potentials without adding to every file at the start.
Cheers.
