### ISSUE TITLE
Set up whyDidYouRender for storybook

### ISSUE THREAD

**Issue by karasavm** [welldone-software/why-did-you-render#93]
I did not manage to set up why did you render on a story book application where I develop my components. Does anyone know how this can be done?

**Comment by Hypnosphi** [comment]
@karasavm Hi, I'm a maintainer of Storybook. What did you already try, and which problems did you encounter? It would help if you could set a GitHub repo as a demo

**Comment by ar53n** [comment]
@Hypnosphi Hi, it's just not working with the configuration from Readme

**Comment by vzaidman** [comment]
hey @Hypnosphi!
did you have the chance to look at it yet?

**Comment by Hypnosphi** [comment]
I don't know what to look at. I use WDYR with storybook without any problems

**Comment by vzaidman** [comment]
ok thanks

**Comment by danvk** [comment]
In case it helps anyone else, I got this to work by creating a module `wdyr.js`:

```js
import React from 'react';

const whyDidYouRender = require('@welldone-software/why-did-you-render');
whyDidYouRender(React, {
  trackAllPureComponents: true,
});
```

and then imported this on the top line of my story file:

```js
import './wdyr';
```

**Comment by vzaidman** [comment]
or, even better, one of the main files like `config.js` so you won't need to do it for every story.

**Comment by danvk** [comment]
@vzaidman I tried sticking that block in `.storybook/main.js` but couldn't get it to work. If there's a way to do this I'd like to see a code sample.

**Comment by Hypnosphi** [comment]
`main.js` doesn't execute on client, you want to use `preview.js`

**Comment by jcolmenarez** [comment]
> I don't know what to look at. I use WDYR with storybook without any problems

It would be nice to see a fully working example, with all of the details on the implementation. I have been struggling for hours now to make this work and it is simply not logging anything at all.

Just in case, here's what I've done so far:

- Added `importSource: '@welldone-software/why-did-you-render'` to the Babel presets options in the `main.js` file, while still keeping `runtime: 'automatic'` and `develop: true`,
- Tried importing the `wdyr.js` file and regular `import whyDidYouRender from '@welldone-software/why-did-you-render'` on the `preview.js ` file (for the latter approach I initialized the `whyDidYouRender(React, { trackAllPureComponents: true })`),
- Confirmed I'm using pure components with React.memo, and even replicated the examples from your official CodeSandbox directly into any story, still not logs at all.

Any info will be much appreciated @Hypnosphi .

Currently using:
- Storybook 6.3.7 & React 16.14.0

**Comment by Hypnosphi** [comment]
@jcolmenarez

> Added importSource: '@welldone-software/why-did-you-render' to the Babel presets options in the main.js file, while still keeping runtime: 'automatic' and develop: true,

How exactly do you do it? Can you please share your `main.js` or, even better, create a reproduction repo?

**Comment by flora8984461** [comment]
I cannot make it work with storybook as well. 

I created a `wdyr.js` file:

// .storybook/wdyr.js
```
import React from 'react';

const whyDidYouRender = require('@welldone-software/why-did-you-render');
whyDidYouRender(React, {
  trackAllPureComponents: true,
  trackHooks: true
});
```

And I imported it on the top in file `.storybook/preview.js`. (It's the root storybook folder)

// .storybook/preview.js
```
import './wdyr';
import React from 'react';
...

const withTheme = (StoryFn, context) => 
return (
<ThemeProvider>
<StoryFn />
</ThemeProvider>
)
```

I also added `MyComponent.whyDidYouRender = true;` in my component file (`MyComponent.tsx`).
(Note my component use typescript to develop, this will give me a type error, I added ts-ignore comment; because I cannot import `wdyr.ts` in `.storybook/preview.js`). I don't have any logs. 

It would be nice to have a working example (and with typescript that would be great!). 

Any help is much appreciated!

**Comment by piyush-toddleapp** [comment]
Hey guys, does any have a working example of wdyr with storybook?

I have tried the different steps as mentioned in the whole thread and I can't make it work properly. The changes are logged but not always and It's like there is a specific case where the changes will be displayed.
One of them being when I have used the component(with wdyr enabled) inside another component and that too not always.

**Comment by JewNinja** [comment]
Perhaps everything "works" you just don't know about it.
After I wasted a lot of corporate time and dug up all their code, I got it working.

Add everything you need to the main.ts to Babel settings. Be careful with the syntax. In my case it looks like this:
`babel: async (options) => ({
    ...options,
    presets: [
      [
        "@babel/preset-env",
        {
          "targets": {
            "chrome": 100,
            "safari": 15,
            "firefox": 91
          },
        },
      ],
      "@babel/preset-typescript",
      [
        "@babel/preset-react",
        {
          "runtime": "automatic",
          "develop": true,
          "importSource": "@welldone-software/why-did-you-render"
        }
      ]
    ]
  })`
  
  Then add to the preview.tsx this or add it like a wdyr.js file and import it as the first import:
  `import React from "react";

if (process.env.NODE_ENV === 'development') {
  const whyDidYouRender = require('@welldone-software/why-did-you-render');
  whyDidYouRender(React, {
    trackAllPureComponents: true,
    include: [/ComponentName/],  // it's needed if you don't add ComponentName.whyDidYouRender = true; to your components
    notifier: console.log,  // often everything works, but the default built-in logger does not respond to changes and you do not see anything, you can try this first
    logOnDifferentValues: true // this is just one of the possible settings so that the logger starts to react to at least something
  });
}`

Your component:
`const Component = forwardRef(
  function forwardedComponent(props, ref) {
    useSomeHooks();

    return <SomeJSX />;
  }
);

Component.whyDidYouRender = true; // typing complains, but that's how it worked for me. Or you can use include: [] in the preview.tsx

export default Component;`

I hope this will help someone. I already realized in the middle of the research that I probably won't use it and finished the search so that the work wouldn't be wasted))
